base_config: "config/base.yaml"

parameters:
  - name: "global_lr"
    path: "synapses.global_lr"
    values: [0.001, 0.005, 0.01, 0.02, 0.03, 0.05]
    #values: [0.001, 0.005]

  - name: "base_Wmax"
    path: "synapses.base_Wmax"
    values: [1, 2, 5, 10, 20, 40, 60, 100]
    #values: [1, 2]