base_config: "config/base_sweeps.yaml"

search:
  lambda_E:
    #values: [1e-4, 3e-4,]
    values: [0.01, 0.015, 0.022, 0.03, 0.04]
  eta_IH:
    #values: [1e-4, 3e-4,]
    values: [0.003, 0.008, 0.015, 0.02, 0.03]
  eta_IA:
    #values: [1e-4, 3e-4,]
    values: [0.003, 0.008, 0.015, 0.02, 0.03]

# optional: weitere Parameter
#  base_Wmax:
#    values: [0.5, 1.0, 2.0]